name: Linux Build

on:
  pull_request:
    branches:
      - develop
      - release*
    paths-ignore:
      - 'docs/**'
      - 'roadmap/**'
      - 'static-builds/**'
      - 'whitepaper/**'
      - 'binaries/**'
      - 'contrib/**'
env:
  OS: linux
  SCRIPTS: ${{ GITHUB.WORKSPACE }}/.github/scripts

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v1

    - name: Install Build Tools
      run: sudo ${SCRIPTS}/00-install-deps.sh ${OS}

    - name: Copy Build Dependencies
      run: ${SCRIPTS}/02-copy-build-dependencies.sh ${OS} ${{ GITHUB.WORKSPACE }}

    - name: Add Dependencies to the System PATH
      run: ${SCRIPTS}/03-export-path.sh ${OS} ${{ GITHUB.WORKSPACE }}

    - name: Build Config
      run: cd ${{ GITHUB.WORKSPACE }} && ./autogen.sh

    - name: Configure Build
      run: ${SCRIPTS}/04-configure-build.sh ${OS} ${{ GITHUB.WORKSPACE }}

    - name: Build Hive
      run: make -j2

    - name: Check Binary Security
      run: make -C src check-security

    - name: Running Unit Tests
      run: make check

    - name: Running Functional Tests
      run: ${{ GITHUB.WORKSPACE }}/src/test/test_hive

    - name: Package Up the Build
      run: ${SCRIPTS}/05-package.sh ${OS} ${{ GITHUB.WORKSPACE }} ${{ GITHUB.BASE_REF }}

    - name: Upload Build to the Nightly Site
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        SOURCE_DIR: "${{ GITHUB.WORKSPACE }}/release/"
        DEST_DIR: 'dev-builds/linux/'
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Upload Artifacts to Job
      uses: actions/upload-artifact@master
      with:
        name: hive-linux
        path: ${{ GITHUB.WORKSPACE }}/release
